---
- name: Creates directory
  file:
    path: ~/server
    state: directory

- name: "extract artifact."
  unarchive:
    src: "files/artifact.tar.gz"
    dest: "~/server"

# - name: "stop app."
#   become: true
#   shell: pm2 stop default
#   ignore_errors: yes

- name: "Executing Node app with PM2"
  shell: |
    cd ~/server/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node