---
- name: Creates directory
  file:
    path: ~/server
    state: directory

- name: "extract artifact."
  unarchive:
    src: "files/artifact.tar.gz"
    dest: "~/server"

- name: "stop app."
  become: true
  shell: pm2 stop default
  ignore_errors: yes

- name: "start server"
  become: true
  shell: |
    cd ~/server
    npm install
    pm2 start npm -- start