---
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: Creates directory
  file:
    path: ~/server
    state: directory

- name: Copy index test page
  template:
    src: "artifact.tar.gz"
    dest: "~/server/artifact.tar.gz"

- name: "extract the zipped artifact"
  become: true
  shell: |
    cd ~/server
    tar -xf artifact.tar.gz

- name: "start server"
  become: true
  shell: |
    cd ~/server
    npm install
    pm2 stop default
    pm2 start npm -- start