---
- name: Creates directory
  file:
    path: /home/ubuntu/server
    state: directory

- name: "extract artifact."
  unarchive:
    src: "files/artifact.tar.gz"
    dest: "/home/ubuntu/server"

- name: "stop app."
  become: true
  shell: |
    cd /home/ubuntu/server
    pm2 stop default
  ignore_errors: yes

- name: "start server"
  become: true
  shell: |
    cd /home/ubuntu/server
    pm2 delete default
    pm2 start npm -- start
